# This is a basic workflow to help you get started with Actions

name: DRaw-cicd-workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for every branch
  push:
    branches:
      - 'master'
      - 'main'
  pull_request:
    types: [ opened, reopened ]
    branches:
      - '*'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: [ubuntu-20.04] # [ubuntu-20.04, windows-latest, macOS-latest]
        dc: [dmd-latest]
        exclude:
          - { os: macOS-latest, dc: dmd-2.085.0 }

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install D Compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      # Runs a set of commands using the runners shell
      - name: Run a Multi-Line Script
        run: |
          echo Check dub and dmd versions:
          dub --version
          dmd --version
          pwd

      ###
      ### Client:
      ###

      # Runs a single command using the runners shell
      - name: Check Client Formatting
        run: sh ./support/cicd_scripts/check_format.sh ./client-and-server/client

      - name: Generate Client Coverage
        working-directory: ./client-and-server/client
        run: dub -b cov

      - name: Check Client Coverage
        run: sh ./support/cicd_scripts/check_coverage.sh ./client-and-server/client

      - uses: actions/upload-artifact@v3
        with:
          name: Client Coverage
          path: ./client-and-server/client/coverage # or path/to/artifact
          retention-days: 5

      - name: Perform Client Unit Tests
        working-directory: ./client-and-server/client
        run: dub run --build=unittest

      - name: Check Client Docs
        working-directory: ./client-and-server/client
        run: sh ../../support/cicd_scripts/check_docs.sh

      - uses: actions/upload-artifact@v3
        with:
          name: Client Docs
          path: ./client-and-server/client/docs # or path/to/artifact
          retention-days: 5

      - name: Build Client Release Deliverables
        working-directory: ./client-and-server/client
        run: |
          dub --build=release
          ls ./bin

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'macOS-latest'
        with:
          name: Client macOS Release Deliverable
          path: ./client-and-server/client/bin/client # or path/to/artifact
          retention-days: 5

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-20.04'
        with:
          name: Client Ubuntu-20.04 Release Deliverable
          path: ./client-and-server/client/bin/client # or path/to/artifact
          retention-days: 5

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: Client Windows Release Deliverable
          path: ./client-and-server/client/bin/client.exe # or path/to/artifact
          retention-days: 5

      ###
      ### Server:
      ###

      - name: Check Server Formatting
        run: sh ./support/cicd_scripts/check_format.sh ./client-and-server/server

      - name: Generate Server Coverage
        working-directory: ./client-and-server/server
        run: dub -b cov

      - name: Check Server Coverage
        run: sh ./support/cicd_scripts/check_coverage.sh ./client-and-server/server

      - uses: actions/upload-artifact@v3
        with:
          name: Server Coverage
          path: ./client-and-server/server/coverage # or path/to/artifact
          retention-days: 5

      # Runs a single command using the runners shell
      - name: Perform Server Unit Tests
        working-directory: ./client-and-server/server
        run: dub run --build=unittest

      - name: Check Server Docs
        working-directory: ./client-and-server/server
        run: sh ../../support/cicd_scripts/check_docs.sh

      - uses: actions/upload-artifact@v3
        with:
          name: Server Docs
          path: ./client-and-server/server/docs # or path/to/artifact
          retention-days: 5

      - name: Build Server Release Deliverables
        working-directory: ./client-and-server/server
        run: |
          dub --build=release
          ls ./bin

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'macOS-latest'
        with:
          name: Server macOS Release Deliverable
          path: ./client-and-server/server/bin/server # or path/to/artifact
          retention-days: 5

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'ubuntu-20.04'
        with:
          name: Server Ubuntu-20.04 Release Deliverable
          path: ./client-and-server/server/bin/server # or path/to/artifact
          retention-days: 5

      - uses: actions/upload-artifact@v3
        if: matrix.os == 'windows-latest'
        with:
          name: Server Windows Release Deliverable
          path: ./client-and-server/server/bin/server.exe # or path/to/artifact
          retention-days: 5
