# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for every branch
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test"
  test:
    name: Dub Tests
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        dc: [dmd-latest]
        exclude:
          - { os: macOS-latest, dc: dmd-2.085.0 }

    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Check dub and dmd versions:
          dub --version
          dmd --version
          pwd

      # Runs a single command using the runners shell
      - name: Perform unit tests
        working-directory: ./client
        run: dub test

      # Runs a single command using the runners shell
      - name: Perform unit tests
        working-directory: ./client
        run: dub run --build=unittest

      - name: Check formatting
        run: sh ./support/cicd_scripts/format.sh ./client
